# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=128)),
                ('login_at', models.DateTimeField(auto_now=True)),
                ('logout_at', models.DateTimeField(auto_now=True)),
                ('age', models.SmallIntegerField(null=True)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('1', '\u7537'), ('2', '\u5973')], default='1', max_length=64)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TechType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', '\u4f01\u4e1a'), ('2', '\u4e2a\u4eba'), ('3', '\u56e2\u4f53')], default='1', max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_team',
            field=models.ManyToManyField(blank=True, related_name='profile', to='account.Profile_Team'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ttype',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ttype', to='account.TechType'),
        ),
    ]
